// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://homngzayiztpjorntgpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvbW5nemF5aXp0cGpvcm50Z3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzU4NTksImV4cCI6MjA2MzgxMTg1OX0.M6VhWTC7eLNKzppgf1RiQ6fXuyOzSdFo8NxYP8HM1bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);